### ISSUE TITLE
Issues with Openstack Metadata network @ 169.254.169.254

### ISSUE THREAD

**Issue by hbonath** [reyk/cloud-agent#3]
Hello, I am testing out cloud-agent installed from pkg_add on OpenBSD 6.4 on OpenStack Rocky on KVM.

I am not a developer, and am not able to edit C code, but wanted to point out an issue I ran into in my lab.

When cloud-agent starts, I get a connection refused as my DHCP endpoint is not the IP that the metadata service runs on, 169.254.169.254 is.

Output from running with the -v option: 
```vio0: bound to 172.31.248.28 from 172.31.248.10 (fa:16:3e:06:d7:85)
dhcp_getendpoint: 172.31.248.10
cloud-agent: http://172.31.248.10/openstack/latest/meta_data.json: Connection refused
dhcp_getendpoint: 172.31.248.10
cloud-agent: http://172.31.248.10/latest/meta-data/instance-id: Connection refused
```

Once I get logged in, if I use curl to fetch the url: http://169.254.169.254/openstack/latest/meta_data.json it works fine.

It would appear that something might need to be added in order to either override, like an option to add a custom metadata IP in the hostname.if file, or perhaps something in the openstack.c to test 169.254.169.254 for connectivity, and use it.

Thank you for your consideration!

**Comment by reyk** [comment]
Sorry for the late reply. I think this is due to one of the last changes that I did for cloudstack because it uses the DHCP-supplied server instead of 169.254.169.254. I will get back at it as soon as I fixed cloud-agent's cms on 6.5.

**Comment by hbonath** [comment]
No worries, that is great - I just wanted to get the issue logged so that it could ultimately be addressed.
I appreciate you taking the time to get this looked into!

**Comment by reyk** [comment]
I changed the logic and it should work with the latest version from HEAD now.

**Comment by hbonath** [comment]
Confirmed fixed! Thank you!
However I did find another related problem, which I'll open a new issue for.
